"""empty message

Revision ID: 06e0d67a9f87
Revises: 07e1af703446
Create Date: 2024-07-17 09:36:55.752996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e0d67a9f87'
down_revision = '07e1af703446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_in')
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.alter_column('starship_name',
               existing_type=sa.VARCHAR(),
               nullable='False')
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable='False')
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('starship_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.create_table('sign_in',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='sign_in_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sign_in_pkey')
    )
    # ### end Alembic commands ###
