"""Add ON DELETE CASCADE to character_id and planet_id

Revision ID: 62029f7f7106
Revises: dfda87e2604d
Create Date: 2024-07-22 15:13:47.804522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62029f7f7106'
down_revision = 'dfda87e2604d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_favorite', schema=None) as batch_op:
        batch_op.drop_constraint('character_favorite_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character', ['character_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('planet_favorite', schema=None) as batch_op:
        batch_op.drop_constraint('planet_favorite_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable='False')
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable='False')
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(),
               nullable='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('planet_favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planet_favorite_planet_id_fkey', 'planet', ['planet_id'], ['id'])

    with op.batch_alter_table('character_favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_favorite_character_id_fkey', 'character', ['character_id'], ['id'])

    # ### end Alembic commands ###
